### ISSUE TITLE
Boundary issue using UIKit Dynamics.

### ISSUE THREAD

**Issue by nihilenz** [TeehanLax/UIViewController-Transitions-Example#3]
Hello, 
after showing the left view controller using UIKit Dynamics, view's x-origin is sometimes 0.5f. You can notice that white line on the left side.
I can just adjust the frame at the end of the animation, but I can not prevent that the line appears during the animation. Can you help me? Thanks!

**Comment by ashfurrow** [comment]
Hi there,

This is actually a bug in UIKit dynamics. I've already filed a radar for Apple to fix it. In the mean time, you need to override the `setFrame:` method to look something like the following:

```
-(void)setFrame:(CGRect)frame {
    [super setFrame:CGRectIntegral(frame)];
}
```

That will make sure that you only have round numbers in your frame origin.

**Comment by nihilenz** [comment]
Hello, thanks!
I subclassed the root `view` of the VC to override `setFrame:` but it does not help
Without success, I also tried to adjust  `toViewController.view.frame` (with `CGRectIntegral`) in  `finishInteractiveTransition`. Other tips? Thank you very much!

**Comment by ashfurrow** [comment]
Really? That's strange. Overriding the `setFrame:` method should definitely work. Can you post the project so I can take a look?

**Comment by nihilenz** [comment]
Just forked and added a UIView subclass (TLMenuView) for TLMenuViewController  https://github.com/nihilenz/UIViewController-Transitions-Example
Thanks!

**Comment by ashfurrow** [comment]
D'oh! My mistake. `setFrame:` won't do anything since `UIDynamicItem`s don't use `setFrame:`, they use `setCenter:` and `setBounds:`. Here's the code I used in a project, you may need to modify it for your own needs. Please let me know if this works. 

```
-(void)setCenter:(CGPoint)center {
    if (center.x < 1) {
        center.x = 0;
    }

    [super setCenter:center];
}
```

**Comment by nihilenz** [comment]
In this way it works very well! Thank you very much ;)

```
- (void)setCenter:(CGPoint)center
{
    if (center.x > 160) {
        center.x = 160;
    }

    [super setCenter:center];
}
```
